// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class DeviceData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject deviceDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.DeviceData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Time("Time"),
		App_id("App_id"),
		Dev_id("Dev_id"),
		Battery("Battery"),
		Event("Event"),
		Light("Light"),
		Temperature("Temperature");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DeviceData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.DeviceData"));
	}

	protected DeviceData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject deviceDataMendixObject)
	{
		if (deviceDataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.DeviceData", deviceDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.DeviceData");

		this.deviceDataMendixObject = deviceDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DeviceData.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.DeviceData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.DeviceData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.DeviceData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.DeviceData(context, mendixObject);
	}

	public static myfirstmodule.proxies.DeviceData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.DeviceData.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.DeviceData> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.DeviceData> result = new java.util.ArrayList<myfirstmodule.proxies.DeviceData>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.DeviceData" + xpathConstraint))
			result.add(myfirstmodule.proxies.DeviceData.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Time
	 */
	public final java.util.Date getTime()
	{
		return getTime(getContext());
	}

	/**
	 * @param context
	 * @return value of Time
	 */
	public final java.util.Date getTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Time.toString());
	}

	/**
	 * Set value of Time
	 * @param time
	 */
	public final void setTime(java.util.Date time)
	{
		setTime(getContext(), time);
	}

	/**
	 * Set value of Time
	 * @param context
	 * @param time
	 */
	public final void setTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date time)
	{
		getMendixObject().setValue(context, MemberNames.Time.toString(), time);
	}

	/**
	 * @return value of App_id
	 */
	public final java.lang.String getApp_id()
	{
		return getApp_id(getContext());
	}

	/**
	 * @param context
	 * @return value of App_id
	 */
	public final java.lang.String getApp_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.App_id.toString());
	}

	/**
	 * Set value of App_id
	 * @param app_id
	 */
	public final void setApp_id(java.lang.String app_id)
	{
		setApp_id(getContext(), app_id);
	}

	/**
	 * Set value of App_id
	 * @param context
	 * @param app_id
	 */
	public final void setApp_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String app_id)
	{
		getMendixObject().setValue(context, MemberNames.App_id.toString(), app_id);
	}

	/**
	 * @return value of Dev_id
	 */
	public final java.lang.String getDev_id()
	{
		return getDev_id(getContext());
	}

	/**
	 * @param context
	 * @return value of Dev_id
	 */
	public final java.lang.String getDev_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Dev_id.toString());
	}

	/**
	 * Set value of Dev_id
	 * @param dev_id
	 */
	public final void setDev_id(java.lang.String dev_id)
	{
		setDev_id(getContext(), dev_id);
	}

	/**
	 * Set value of Dev_id
	 * @param context
	 * @param dev_id
	 */
	public final void setDev_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dev_id)
	{
		getMendixObject().setValue(context, MemberNames.Dev_id.toString(), dev_id);
	}

	/**
	 * @return value of Battery
	 */
	public final java.lang.Integer getBattery()
	{
		return getBattery(getContext());
	}

	/**
	 * @param context
	 * @return value of Battery
	 */
	public final java.lang.Integer getBattery(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Battery.toString());
	}

	/**
	 * Set value of Battery
	 * @param battery
	 */
	public final void setBattery(java.lang.Integer battery)
	{
		setBattery(getContext(), battery);
	}

	/**
	 * Set value of Battery
	 * @param context
	 * @param battery
	 */
	public final void setBattery(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer battery)
	{
		getMendixObject().setValue(context, MemberNames.Battery.toString(), battery);
	}

	/**
	 * @return value of Event
	 */
	public final java.lang.String getEvent()
	{
		return getEvent(getContext());
	}

	/**
	 * @param context
	 * @return value of Event
	 */
	public final java.lang.String getEvent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Event.toString());
	}

	/**
	 * Set value of Event
	 * @param event
	 */
	public final void setEvent(java.lang.String event)
	{
		setEvent(getContext(), event);
	}

	/**
	 * Set value of Event
	 * @param context
	 * @param event
	 */
	public final void setEvent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String event)
	{
		getMendixObject().setValue(context, MemberNames.Event.toString(), event);
	}

	/**
	 * @return value of Light
	 */
	public final java.lang.Integer getLight()
	{
		return getLight(getContext());
	}

	/**
	 * @param context
	 * @return value of Light
	 */
	public final java.lang.Integer getLight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Light.toString());
	}

	/**
	 * Set value of Light
	 * @param light
	 */
	public final void setLight(java.lang.Integer light)
	{
		setLight(getContext(), light);
	}

	/**
	 * Set value of Light
	 * @param context
	 * @param light
	 */
	public final void setLight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer light)
	{
		getMendixObject().setValue(context, MemberNames.Light.toString(), light);
	}

	/**
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature()
	{
		return getTemperature(getContext());
	}

	/**
	 * @param context
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Temperature.toString());
	}

	/**
	 * Set value of Temperature
	 * @param temperature
	 */
	public final void setTemperature(java.math.BigDecimal temperature)
	{
		setTemperature(getContext(), temperature);
	}

	/**
	 * Set value of Temperature
	 * @param context
	 * @param temperature
	 */
	public final void setTemperature(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal temperature)
	{
		getMendixObject().setValue(context, MemberNames.Temperature.toString(), temperature);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return deviceDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.DeviceData that = (myfirstmodule.proxies.DeviceData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.DeviceData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
